import Head from 'next/head'
import Link from 'next/link'
import SocialLinks from '../components/SocialLinks'

const sectionProps: string = 'flex h-screen w-auto flex-col items-center justify-center'

export default function Home() {
  return (
    <div className='bg-slate-900 min-h-screen dark:text-slate-100'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>

      <main>
        {/* name and links */}
        <div className='flex h-screen w-auto flex-col items-center justify-center pt-9'>
          <h1 className='text-center text-4xl font-bold font-sans dark:text-gray-200'>neocodes</h1>
          <h2 className='text-center'>anzle chavez &#xb7; <a href="mailto:anzlemchavez@gmail.com" className='dark: text-gray-200 hover:text-blue-300'>anzlemchavez@gmail.com</a></h2>
          <SocialLinks className='pt-3' />
          <div className='flex flex-row justify-center gap-3 pt-3'>
            <nav>projects &#xb7;</nav>
            <Link href="/expo86">
              <a>Expo 86</a>
            </Link>
          </div>
        </div>
        {/* introduction */}
      </main>
    </div>
  )
}
