import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='bg-slate-800 min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>

      <main className='pt-10'>
        <h1 className='text-center text-4xl font-bold font-sans dark:text-gray-200'>neocodes</h1>
        <h2 className='text-center dark:text-gray-200'>anzle chavez &#xb7; <a href="mailto:anzlemchavez@gmail.com" className='dark: text-gray-200 hover:text-blue-300'>anzlemchavez@gmail.com</a></h2>
      </main>
    </div>
  )
}
